apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-app
  labels:
    app: net-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-app
  template:
    metadata:
      labels:
        app: net-app
    spec:
      containers:
      - name: net-app
        image: master101/net_clone:latest
        ports:
        - containerPort: 3000
